name:  Creando un fichero - RLLM
 
on:
  workflow_dispatch:
 
jobs:
  saludo:
    runs-on: labs-runner
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
 
      - name: Llamando a la acción personalizada
        uses: ./.github/actions/action_1
        with:
          mensaje: "Hola soy Roy y este es mi mensaje personalizado"