name: Subida y Bajada de Artefactos - RLLM

on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: labs-runner
    steps:
      - name: Hacemos checkout del repositorio
        uses: actions/checkout@v3

      - name: Subimos el artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-subido
          path: artefactoRLLM.txt

  download-artifact:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-subido

      - name: Mostrar contenido del archivo
        run: cat artefactoRLLM.txt
