name: "Información del runner - RLLM"

on:
  workflow_dispatch:

jobs:
  runner-info:
    runs-on: labs-runner

    steps:
      - name: Mostrando información del runner
        run: echo "Sistema Operativo: ${{ runner.os }}"

      - name: Mostrando arquitectura del runner
        run: echo "Arquitectura: ${{ runner.arch }}"

      - name: Mostrando espacio disponible del disco del runner
        run: df -h