name: "Trigger diario - RLLM"

on:
  schedule:
    - cron: "0 12 * * *"  # Todos los días a las 12:00 UTC

jobs:
  scheduled-job:
    runs-on: labs-runner

    steps:
      - name: Imprimir mensaje
        run: echo "Scheduled job executed!"