name: "Creando un nuevo Issue - RLLM"

on:
  issues:
    types: [opened]

jobs:
  issue-created:
    runs-on: labs-runner

    steps:
      - name: Imprimir mensaje
        run: echo "Has creado un nuevo issue en el repositorio"