name: "Trigger de pull request en una rama - RLLM"

on:
  pull_request:
    branches:
      - main
      - soluciones-rllm
jobs:
  build:
    runs-on: labs-runner
    steps:
      - run: echo "Este es un trigger en la rama main"