name: "Variables por jobs - RLLM"

on:
  workflow_dispatch:

jobs:
  variables_locales_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Variable local (JOB 1)
        run: |
          var1=1
          echo "El contenido de var1 es: $var1"
      
      - name: Variable de entorno (JOB 1)
        run: echo "var2=2" >> $GITHUB_ENV

      - name: Usando var2
        run: |
          echo "El contenido de var2 es: $var2"

  step_outputs_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Definiendo output
        id: paso1
        run: echo "var_step_output=valor" >> $GITHUB_OUTPUT

      - name: Usando output
        run: |
         echo "El valor de var_step_output es: ${{ steps.paso1.outputs.var_step_output }}"

  definir_output_job3:
    runs-on: ubuntu-latest
    outputs:
      var3: ${{ steps.setvar3.outputs.var3 }}
    steps:
      - name: Imprimir var2
        run: |
          echo "El valor de var2 es: $var2"

      - name: Definir output var3
        id: setvar3
        run: echo "var3=3" >> $GITHUB_OUTPUT

  usar_output_job4:
    needs: definir_output_job3
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo output var3
        run: | 
          echo "El valor del output var3 es: ${{ needs.definir_output_job3.outputs.var3 }}"

  github_vars_job5:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrando variables definidas por GitHub
        run: |
          echo "El nombre del repositorio es: ${{ github.repository }}"
          echo "El nombre de la rama es: ${{ github.ref_name }}"
          echo "El nombre del evento que activo el workflow es: ${{ github.event_name }}"