name: "Usando Variables - RLLM"

on:
  workflow_dispatch:

jobs:
  variables-job:
    runs-on: ubuntu-latest

    steps:
      - name: Definiendo variables de entorno
        shell: bash
        run: echo "NOMBRE=Roy" >> $GITHUB_ENV
        run: echo "CURSO=GitHub Actions por Stemdo" >> $GITHUB_ENV

      - name: Usando las variables de entorno
        run: |
          echo "Hola, me llamo $NOMBRE y estoy aprendiendo $CURSO"